particle_map:
  frame_id: world
  cx: 320.5
  cy: 240.5
  fx: 554.254691191187
  fy: 554.254691191187
  use_depth_filter: false
  k_depth_scaling_factor: 1000.0
  skip_pixel: 2

  # camera parameters need 

  odom_lidar_timeout: 0.35
  local_update_range_x: 5
  local_update_range_y: 5
  local_update_range_z: 1.5
  inf_grid: 1
  enable_virtual_wall: true

  virtual_ceil: 3.0

  virtual_ground: -0.1
  ground_height: 0.01
  fov_horizontal_lowbound: -180
  fov_horizontal_upbound: 180 
  fov_vertical_lowbound: -50
  fov_vertical_upbound: 50
  occupancy_thresh: 0.6
  risk_thresh: 0.15
  risk_point_gate: 10
  enable_future_prediction: false
  dynamic_cluster_max_center_height: 20.0
  dynamic_cluster_max_point_num: 2008
  position_prediction_stddev: 0.05
  velocity_prediction_stddev: 0.05
  new_born_particle_weight: 0.0001
  new_born_particle_number_each_point: 20
  voxel_filter_resolution: 0.2
  sigma_ob: 0.1
  kappa: 0.01
  P_detection: 0.95